server:
  port: 8082

spring:
  application:
    name: product-service
  
  data:
    mongodb:
      uri: mongodb://localhost:27017/productdb
      auto-index-creation: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true

logging:
  level:
    com.ecommerce.productservice: DEBUG

---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://admin:password@mongodb:27017/productdb?authSource=admin}